apiVersion: v1
kind: Service
metadata:
  name: clusterip-service-pod
spec:
  type: ClusterIP
  externalIPs:
  - 10.178.0.24
  selector:
    app: web-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
