apiVersion: v1
kind: Service
metadata:
  name: nodeport-service-pod
spec:
  type: NodePort
  selector:
    app: web-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
