apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service-pod
spec:
  type: LoadBalancer
  externalIPs:
  - 10.178.0.25
  selector:
    app: web-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
